image: ubuntu18.04
version: '1.0.{build}'
shallow_clone: false
skip_branch_with_pr: true
services:
- docker

branches:
  only:
    - master

environment:
  NUGET_API:
    secure: 7zpjFrJRFYqsLO6bOzzntKph8Bg1OMrMAvJnfPduGVAiMItbjpaHqCAiWy2qu/d3

install:

build: off

build_script:
  - cd src/TeamsidToBitwardenConverter
  - docker build -t teamsidToBitwardenConverter -f Dockerfile .
  - docker run -it --rm -v ${APPVEYOR_BUILD_FOLDER}/src/TeamsidToBitwardenConverter/pack:/app/pack teamsidToBitwardenConverter

test_script:

deploy:
  - provider: NuGet
    api_key:
      secure: 
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
