image: Ubuntu1804
version: '1.0.{build}'
shallow_clone: false
skip_branch_with_pr: true
services:
- docker

environment:
  nuget_api_key:
    secure: jOYZDcIjrIQs9VOXOvhBVzVxmwkzBmeEebbRjv3DlemfWmzHW179DqSONfRKYE2/
branches:
  only:
    - master

install:

build: off

build_script:
  - cd src/TeamsidToBitwardenConverter
  - docker build -t teamsidtobitwardenconverter -f Dockerfile .
  - docker run -i --rm -v ${APPVEYOR_BUILD_FOLDER}/src/TeamsidToBitwardenConverter/pack:/app/pack teamsidtobitwardenconverter

test_script:

deploy_script:
  - if [ ${APPVEYOR_REPO_TAG} = "true" ]; then dotnet nuget push ${APPVEYOR_BUILD_FOLDER}/src/TeamsidToBitwardenConverter/pack/*.nupkg -k ${nuget_api_key} -s https://api.nuget.org/v3/index.json -ss https://nuget.smbsrc.net ; fi
